[phases.setup]
nixPkgs = ["nodejs_22", "npm-10_x"]

[phases.install]
commands = ["npm ci"]

[phases.build]
commands = [
  "if [ \"$NEXT_PUBLIC_APP_ENV\" = \"seller\" ]; then npm run build:seller; elif [ \"$NEXT_PUBLIC_APP_ENV\" = \"inspector\" ]; then npm run build:inspector; else npm run build; fi"
]

[start]
cmd = "npm run start"
