[phases.setup]
nixPkgs = ["nodejs_22", "npm-10_x"]

[phases.install]
commands = ["npm ci"]

[phases.build]
commands = [
  "if [ \"$BUILD_MODE\" = \"seller\" ]; then npm run build:seller; elif [ \"$BUILD_MODE\" = \"inspector\" ]; then npm run build:inspector; else npm run build; fi"
]

[start]
cmd = "npm run start"
